sudo: required
services:
  - docker

before_install:
  - docker build -t abdulwahabameth/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abdulwahabameth/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "me-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-me-south-1-382487711276"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
