sudo: required
services:
  - docker

before_install:
  - docker build -t abdulwahabameth/docker-react -f Dockerfile.dev .

script:
  - docker run abdulwahabameth/docker-react npm run test -- --coverage
